create table smtp (
day Date DEFAULT toDate(ts),
ts DateTime,
uid String,
orig_h String,
orig_p UInt16,
resp_h String,
resp_p UInt16,
trans_depth UInt16,
helo Nullable(String),
mailfrom Nullable(String),
rcptto Array(Nullable(String)),
date Nullable(String),
from Nullable(String),
to Array(Nullable(String)),
reply_to Nullable(String),
in_reply_to Nullable(String),
subject Nullable(String),
x_originating_ip Nullable(String),
first_received Nullable(String),
second_received Nullable(String),
last_reply Nullable(String),
path Array(Nullable(String)),
user_agent String,
tls Enum8('F'=0, 'T'=1),
fuids Array(String),
is_webmail Enum8('F'=0, 'T'=1)
)
ENGINE = MergeTree(day,sipHash64(uid), (day,sipHash64(uid), uid), 8192);
