create table stats (
day Date DEFAULT toDate(ts),
ts DateTime,
peer String,
mem UInt32,
pkts_proc UInt64,
bytes_recv UInt64,
pkts_dropped UInt64,
pkts_link UInt64,
pkt_lag Float32,
events_proc UInt32,
events_queued UInt32,
active_tcp_conns UInt32,
active_udp_conns UInt32,
active_icmp_conns UInt32,
tcp_conns UInt32,
udp_conns UInt32,
icmp_conns UInt32,
timers UInt32,
active_timers UInt32,
files UInt32,
active_files UInt32,
dns_requests UInt64,
active_dns_requests UInt64,
reassem_tcp_size UInt32,
reassem_file_size UInt32,
reassem_frag_size UInt32,
reassem_unknown_size UInt32
)
ENGINE = MergeTree(day, (day, peer), 8192);
